apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Chart.Name}}-create-secret-{{.Release.Name}}"
  labels:
    app: bluecompute
    micro: orders
    tier: backend
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "20"
spec:
  template:
    metadata:
      name: "{{.Chart.Name}}-create-secret-{{.Release.Name}}"
      labels:
        app: bluecompute
        micro: orders
        tier: backend
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      restartPolicy: Never
      containers:
      - name: create-secret
        image: ibmcase/kubectl:latest
        command: [ "/bin/bash", "-c" ]
        args: ["kubectl get secrets bluemix-api-key --namespace {{ .Release.Namespace }} || \
        kubectl create secret generic bluemix-api-key --from-literal=api-key=${BLUEMIX_API_KEY} \
        --namespace {{ .Release.Namespace }}"]
        imagePullPolicy: IfNotPresent
        env:
        - name: BLUEMIX_API_KEY
          value: {{ .Values.secret.apiKey }}