apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Chart.Name}}-cleanup-jobs-{{.Release.Name}}-{{ randAlphaNum 5 | lower }}"
  labels:
    app: bluecompute
    micro: orders
    tier: data
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-delete
    "helm.sh/hook-weight": "39"
spec:
  template:
    metadata:
      name: "{{.Chart.Name}}-cleanup-jobs-{{.Release.Name}}-{{ randAlphaNum 5 | lower }}"
      labels:
        app: bluecompute
        micro: orders
        tier: data
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: cleanup-jobs
        image: ibmcase/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c" ]
        args: 
        - >
            set -x;
            kubectl --namespace {{ Release.Namespace }} delete jobs -l chart={{.Chart.Name}}-{{.Chart.Version}},release={{.Release.Name}} --cascade;

