apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  labels:
    app: bluecompute
    micro: orders
    tier: data
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ports:
    - port: {{ .Values.mysql.service.internalPort }}
      targetPort: {{ .Values.mysql.service.externalPort }}
  selector:
    app: bluecompute
    micro: orders
    tier: data
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"