apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: bluecompute
    micro: orders
    tier: backend
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: bluecompute
        micro: orders
        tier: backend
        release: {{.Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      containers:
      - name: orders
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 8080
        env:
        - name: HS256_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "hs256SecretName" . }}
              key: key 
        - name: mysql
          valueFrom:
            secretKeyRef:
              name: {{ template "mysqlBindingName" . }}
              key: binding
        {{ template "messageHubEnv" . }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
