apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Chart.Name}}-populate-mysql-{{.Release.Name}}"
  labels:
    app: bluecompute
    micro: orders
    tier: backend
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "25"
spec:
  template:
    metadata:
      name: "{{.Chart.Name}}-populate-mysql-{{.Release.Name}}"
      labels:
        app: bluecompute
        micro: orders
        tier: backend
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      restartPolicy: Never
      containers:
      - name: populate-mysql
        image: ibmcase/mysql-loader:latest
        command: [ "/bin/bash", "-c" ]
        args: ["./startup.sh"]
        imagePullPolicy: IfNotPresent
        env:
        - name: mysql
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.mysql.secret }}"
              key: binding