apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: bluecompute
    micro: orders
    tier: backend
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bluecompute
    micro: orders
    tier: backend
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
