apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: bluecompute
    micro: orders
    tier: backend
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: bluecompute
        micro: orders
        tier: backend
        release: {{.Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        volumeMounts:
        - mountPath: /var/run/secrets/binding-refarch-compose-for-mysql
          name: {{ .Values.mysql.binding.name }}
        - mountPath: /var/run/secrets/hs256-key
          name: hs256-key
        ports:
        - containerPort: 8080
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: {{ .Values.mysql.binding.name }}
        secret:
          defaultMode: 420
          secretName: "{{ .Values.mysql.binding.name }}"
      - name: hs256-key
        secret:
          defaultMode: 420
          secretName: "{{ .Chart.Name }}-{{ .Values.hs256key.secretName }}"
